#!/bin/bash
echo "这是一个用于使用在Ubuntu下，利用xray翻墙后，实现kill-switch的脚本和方法，参考了很多博客和教程编写，但仍然可能有漏洞和疏忽的地方"
echo "仅用于学习使用，请勿用于非法用途"
sudo -v
if [ $? -ne 0 ]; then
    echo "无法获取sudo权限，法继续执行。"
    exit 1
fi
sudo apt install ufw -y

sudo chmod 644 /etc/ufw/ufw.conf
sudo chmod 644 /etc/ufw/applications.d
sudo chmod 644 /etc/ufw/user.rules
sudo chmod 644 /etc/ufw/before.rules
sudo chmod 644 /etc/ufw/after.rules
sudo chmod 644 /etc/ufw/user6.rules
sudo chmod 644 /etc/ufw/before6.rules
sudo chmod 644 /etc/ufw/after6.rules

sudo ufw reset
sudo ufw disable 
# Set the default UFW rules to deny incoming and outgoing connections
sudo ufw default deny
sudo ufw default deny incoming
sudo ufw default deny outgoing
#ufw allow out on tun0 from any to any
#ufw allow in on tun0 from any to any#这是如果你连接了Openvpn时，这个是虚拟网卡，允许虚拟网卡内部任意传输流量,xray用不到
# Allow OpenVPN UDP 1194 port through the firewall
ufw allow from 1.1.1.1 to any port 853 proto tcp
#allow  dns  over tls
ufw allow from 172.67.166.125 to any
ufw allow from any  to 172.67.166.125    #放行你的VPS ip,这是cloudflare的ip地址，这里举个例子，强烈建议使用CDN和VMESS+TLS+NGINX反代
echo "设置加密的DNS查询，避免DNS污染"

sudo echo -e "[Resolve]\nDNS=1.1.1.1\nDNSOverTLS=yes">/etc/systemd/resolved.conf

systemctl restart systemd-resolved.service
systemctl restart systemd-resolved
